spring:
  application:
    name: financial-management

  datasource:
    url: jdbc:postgresql://${FINMGMT_POSTGRES_HOST:localhost}:${FINMGMT_POSTGRES_PORT:5432}/${FINMGMT_POSTGRES_DB:finamgmt}
    username: ${FINMGMT_POSTGRES_USER:finamgmt}
    password: ${FINMGMT_POSTGRES_PASSWORD:finamgmt}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs